[package]
name = "procedural-generation-2"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.2", features = ["wayland"] }
bevy-inspector-egui = { version = "0.25.2" }
bevy_pancam = { version = "0.14.0", features = ["bevy_egui"] }
noise = { version = "0.9.0" }
rand = { version = "0.8.5" }
async-std = { version = "1.13.0"}

#[profile.dev]
#opt-level = 1

#[profile.dev.package."*"]
#opt-level = 3

[profile.release]
lto = "thin"
codegen-units = 1

[profile.wasm-release]
inherits = "release"
opt-level = "s"
strip = "debuginfo"