[[states]]
terrain = "Any"
climate = "Moderate"
excluded_objects = [
  "SwampInnerCornerBottomRight",
  "SwampInnerCornerTopRight",
  "SwampInnerCornerBottomLeft",
  "SwampInnerCornerTopLeft",
  "SwampOuterCornerTopLeft",
  "SwampOuterCornerBottomLeft",
  "SwampOuterCornerTopRight",
  "SwampOuterCornerBottomRight",
  "SwampBottomFill",
  "SwampTopFill",
  "SwampLeftFill",
  "SwampRightFill",
  "SwampFill"
]

[[states]]
terrain = "Any"
climate = "Humid"
excluded_objects = [
  "SwampInnerCornerBottomRight",
  "SwampInnerCornerTopRight",
  "SwampInnerCornerBottomLeft",
  "SwampInnerCornerTopLeft",
  "SwampOuterCornerTopLeft",
  "SwampOuterCornerBottomLeft",
  "SwampOuterCornerTopRight",
  "SwampOuterCornerBottomRight",
  "SwampBottomFill",
  "SwampTopFill",
  "SwampLeftFill",
  "SwampRightFill",
  "SwampFill"
]

[[states]]
terrain = "Any"
climate = "Dry"
excluded_objects = [
  "SwampInnerCornerBottomRight",
  "SwampInnerCornerTopRight",
  "SwampInnerCornerBottomLeft",
  "SwampInnerCornerTopLeft",
  "SwampOuterCornerTopLeft",
  "SwampOuterCornerBottomLeft",
  "SwampOuterCornerTopRight",
  "SwampOuterCornerBottomRight",
  "SwampBottomFill",
  "SwampTopFill",
  "SwampLeftFill",
  "SwampRightFill",
  "SwampFill"
]

[[states]]
terrain = "Land2"
climate = "Moderate"
excluded_objects = [
  "SwampInnerCornerBottomRight",
  "SwampInnerCornerTopRight",
  "SwampInnerCornerBottomLeft",
  "SwampInnerCornerTopLeft",
  "SwampOuterCornerTopLeft",
  "SwampOuterCornerBottomLeft",
  "SwampOuterCornerTopRight",
  "SwampOuterCornerBottomRight",
  "SwampBottomFill",
  "SwampTopFill",
  "SwampLeftFill",
  "SwampRightFill",
  "SwampFill"
]

[[states]]
terrain = "Land3"
climate = "Moderate"
excluded_objects = [
  "SwampInnerCornerBottomRight",
  "SwampInnerCornerTopRight",
  "SwampInnerCornerBottomLeft",
  "SwampInnerCornerTopLeft",
  "SwampOuterCornerTopLeft",
  "SwampOuterCornerBottomLeft",
  "SwampOuterCornerTopRight",
  "SwampOuterCornerBottomRight",
  "SwampBottomFill",
  "SwampTopFill",
  "SwampLeftFill",
  "SwampRightFill",
  "SwampFill"
]
