terrain = "Any"

[[states]]
index = 0
name = "Empty"
weight = 225
permitted_neighbours = [
  ["Top", [
    "Empty",
    "Land3RuinTop",
    "Land3RuinRight",
    "Land3RuinLeft",
    "Land3RuinHorizontal",
    "Land3RuinHorizontalLand2Right",
    "Land3RuinHorizontalLand2Left",
    "Land2RubbleTop",
    "Land2RubbleRight",
    "Land2RubbleLeft",
    "Land2RubbleHorizontal",
    "Land2RubbleHorizontalLand3Right",
    "Land2RubbleHorizontalLand3Left",
    "Land2IndividualObject1",
    "Land2IndividualObject2",
    "Land2IndividualObject3",
    "Land2IndividualObject4",
    "Land2IndividualObject5",
    "Land2IndividualObject6",
    "Land2IndividualObject7",
    "Land1PathTop",
    "Land1PathRight",
    "Land1PathLeft",
    "Land1PathHorizontal",
    "Land1StoneTopFill1",
    "Land1StoneTopFill2",
    "Land1StoneTopRightFill",
    "Land1StoneTopLeftFill",
    "Land1StoneRightFill",
    "Land1StoneLeftFill",
    "Land1StoneBottomRightFill",
    "Land1StoneBottomLeftFill",
    "Land1Stone1",
    "Land1Stone2",
    "Land1Stone3",
    "Land1Stone4",
    "Land1Stone5",
    "Land1Stone6",
    "Land1IndividualObject1",
    "Land1IndividualObject2",
    "Land1ConnectedObjectLeft",
    "Land1ConnectedObjectMiddle",
    "Land1ConnectedObjectRight",
    "Land1IndividualObject3",
    "Land1IndividualObject4",
    "Land3Tree1",
    "Land3Tree2",
    "Land3Tree3",
    "Land3Tree4",
    "Land3Tree5",
    "Land3IndividualObject1",
    "Land3IndividualObject2",
    "Land3IndividualObject3",
    "Land3IndividualObject4",
    "Land3IndividualObject5",
    "Land3IndividualObject6",
    "SwampInnerCornerTopRight",
    "SwampInnerCornerTopLeft",
    "SwampTopFill",
    "PathRight",
    "PathHorizontal",
    "PathTop",
    "PathLeft",
    "PathTopRight",
    "PathTopLeft",
    "PathTopHorizontal",
    "HouseSmallWallLeft2",
    "HouseSmallWallRight1",
    "HouseSmallDoorLeft",
    "HouseSmallDoorRight",
    "HouseSmallWallLeft1",
    "HouseSmallWallRight2",
    "HouseMediumWallLeft",
    "HouseMediumDoorMiddle1",
    "HouseMediumWallRight",
    "HouseMediumDoorLeft1",
    "HouseMediumDoorLeft2",
    "HouseMediumWallMiddle1",
    "HouseMediumWallMiddle2",
    "HouseMediumDoorRight1",
    "HouseMediumDoorRight2",
    "HouseMediumDoorMiddle2",
    "HouseLargeWallLeft",
    "HouseLargeDoorMiddle1",
    "HouseLargeWallRight",
    "HouseLargeDoorLeft1",
    "HouseLargeDoorLeft2",
    "HouseLargeWallMiddle1",
    "HouseLargeWallMiddle2",
    "HouseLargeDoorRight1",
    "HouseLargeDoorRight2",
    "HouseLargeDoorMiddle2"
  ]],
  ["Left", [
    "Empty",
    "Land3RuinTop",
    "Land3RuinBottom",
    "Land3RuinLeft",
    "Land3RuinVertical",
    "Land3RuinVerticalLand2Top",
    "Land3RuinVerticalLand2Bottom",
    "Land2RubbleTop",
    "Land2RubbleBottom",
    "Land2RubbleLeft",
    "Land2RubbleVertical",
    "Land2RubbleVerticalLand3Top",
    "Land2RubbleVerticalLand3Bottom",
    "Land2IndividualObject1",
    "Land2IndividualObject2",
    "Land2IndividualObject3",
    "Land2IndividualObject4",
    "Land2IndividualObject5",
    "Land2IndividualObject6",
    "Land2IndividualObject7",
    "Land1PathTop",
    "Land1PathBottom",
    "Land1PathLeft",
    "Land1PathVertical",
    "Land1StoneTopFill1",
    "Land1StoneTopFill2",
    "Land1StoneTopRightFill",
    "Land1StoneTopLeftFill",
    "Land1StoneRightFill",
    "Land1StoneLeftFill",
    "Land1StoneBottomRightFill",
    "Land1StoneBottomLeftFill",
    "Land1Stone1",
    "Land1Stone2",
    "Land1Stone3",
    "Land1Stone4",
    "Land1Stone5",
    "Land1Stone6",
    "Land1IndividualObject1",
    "Land1IndividualObject2",
    "Land1ConnectedObjectRight",
    "Land1IndividualObject3",
    "Land1IndividualObject4",
    "Land3Tree1",
    "Land3Tree2",
    "Land3Tree3",
    "Land3Tree4",
    "Land3Tree5",
    "Land3IndividualObject1",
    "Land3IndividualObject2",
    "Land3IndividualObject3",
    "Land3IndividualObject4",
    "Land3IndividualObject5",
    "Land3IndividualObject6",
    "SwampInnerCornerBottomLeft",
    "SwampInnerCornerTopLeft",
    "SwampLeftFill",
    "PathVertical",
    "PathBottom",
    "PathTop",
    "PathLeft",
    "PathTopLeft",
    "PathBottomLeft",
    "PathLeftVertical",
    "HouseMediumRoofRight1",
    "HouseMediumRoofRight2",
    "HouseMediumRoofRight3",
    "HouseMediumWallRight",
    "HouseLargeRoofRight1",
    "HouseLargeRoofRight2",
    "HouseLargeRoofRight3",
    "HouseLargeWallRight",
    "HouseMediumDoorRight1",
    "HouseMediumDoorRight2",
    "HouseLargeDoorRight1",
    "HouseLargeDoorRight2",
    "HouseSmallRoofRight1",
    "HouseSmallWallRight1",
    "HouseSmallRoofRight2",
    "HouseSmallDoorRight",
    "HouseSmallRoofRight3",
    "HouseSmallWallRight2"
  ]],
  ["Right", [
    "Empty",
    "Land3RuinTop",
    "Land3RuinRight",
    "Land3RuinBottom",
    "Land3RuinVertical",
    "Land3RuinVerticalLand2Top",
    "Land3RuinVerticalLand2Bottom",
    "Land2RubbleTop",
    "Land2RubbleRight",
    "Land2RubbleBottom",
    "Land2RubbleVertical",
    "Land2RubbleVerticalLand3Top",
    "Land2RubbleVerticalLand3Bottom",
    "Land2IndividualObject1",
    "Land2IndividualObject2",
    "Land2IndividualObject3",
    "Land2IndividualObject4",
    "Land2IndividualObject5",
    "Land2IndividualObject6",
    "Land2IndividualObject7",
    "Land1PathTop",
    "Land1PathRight",
    "Land1PathBottom",
    "Land1PathVertical",
    "Land1StoneTopFill1",
    "Land1StoneTopFill2",
    "Land1StoneTopRightFill",
    "Land1StoneTopLeftFill",
    "Land1StoneRightFill",
    "Land1StoneLeftFill",
    "Land1StoneBottomRightFill",
    "Land1StoneBottomLeftFill",
    "Land1Stone1",
    "Land1Stone2",
    "Land1Stone3",
    "Land1Stone4",
    "Land1Stone5",
    "Land1Stone6",
    "Land1IndividualObject1",
    "Land1IndividualObject2",
    "Land1ConnectedObjectLeft",
    "Land1IndividualObject3",
    "Land1IndividualObject4",
    "Land3Tree1",
    "Land3Tree2",
    "Land3Tree3",
    "Land3Tree4",
    "Land3Tree5",
    "Land3IndividualObject1",
    "Land3IndividualObject2",
    "Land3IndividualObject3",
    "Land3IndividualObject4",
    "Land3IndividualObject5",
    "Land3IndividualObject6",
    "SwampInnerCornerBottomRight",
    "SwampInnerCornerTopRight",
    "SwampRightFill",
    "PathRight",
    "PathVertical",
    "PathBottom",
    "PathTop",
    "PathTopRight",
    "PathBottomRight",
    "PathRightVertical",
    "HouseMediumRoofLeft1",
    "HouseMediumRoofLeft2",
    "HouseMediumRoofLeft3",
    "HouseMediumWallLeft",
    "HouseLargeRoofLeft1",
    "HouseLargeRoofLeft2",
    "HouseLargeRoofLeft3",
    "HouseLargeWallLeft",
    "HouseMediumDoorLeft1",
    "HouseMediumDoorLeft2",
    "HouseLargeDoorLeft1",
    "HouseLargeDoorLeft2",
    "HouseSmallRoofLeft1",
    "HouseSmallWallLeft2",
    "HouseSmallRoofLeft2",
    "HouseSmallDoorLeft",
    "HouseSmallRoofLeft3"
  ]],
  ["Bottom", [
    "Empty",
    "Land3RuinRight",
    "Land3RuinBottom",
    "Land3RuinLeft",
    "Land3RuinHorizontal",
    "Land3RuinHorizontalLand2Right",
    "Land3RuinHorizontalLand2Left",
    "Land2RubbleRight",
    "Land2RubbleBottom",
    "Land2RubbleLeft",
    "Land2RubbleHorizontal",
    "Land2RubbleHorizontalLand3Right",
    "Land2RubbleHorizontalLand3Left",
    "Land2IndividualObject1",
    "Land2IndividualObject2",
    "Land2IndividualObject3",
    "Land2IndividualObject4",
    "Land2IndividualObject5",
    "Land2IndividualObject6",
    "Land2IndividualObject7",
    "Land1PathRight",
    "Land1PathBottom",
    "Land1PathLeft",
    "Land1PathHorizontal",
    "Land1StoneTopFill1",
    "Land1StoneTopFill2",
    "Land1StoneTopRightFill",
    "Land1StoneTopLeftFill",
    "Land1StoneRightFill",
    "Land1StoneLeftFill",
    "Land1StoneBottomRightFill",
    "Land1StoneBottomLeftFill",
    "Land1Stone1",
    "Land1Stone2",
    "Land1Stone3",
    "Land1Stone4",
    "Land1Stone5",
    "Land1Stone6",
    "Land1IndividualObject1",
    "Land1IndividualObject2",
    "Land1ConnectedObjectLeft",
    "Land1ConnectedObjectMiddle",
    "Land1ConnectedObjectRight",
    "Land1IndividualObject3",
    "Land1IndividualObject4",
    "Land3Tree1",
    "Land3Tree2",
    "Land3Tree3",
    "Land3Tree4",
    "Land3Tree5",
    "Land3IndividualObject1",
    "Land3IndividualObject2",
    "Land3IndividualObject3",
    "Land3IndividualObject4",
    "Land3IndividualObject5",
    "Land3IndividualObject6",
    "SwampInnerCornerBottomRight",
    "SwampInnerCornerBottomLeft",
    "SwampBottomFill",
    "PathRight",
    "PathHorizontal",
    "PathBottom",
    "PathLeft",
    "PathBottomRight",
    "PathBottomLeft",
    "PathBottomHorizontal",
    "HouseMediumRoofLeft1",
    "HouseMediumRoofLeft2",
    "HouseMediumRoofLeft3",
    "HouseMediumRoofMiddle1",
    "HouseMediumRoofMiddle2",
    "HouseMediumRoofMiddle3",
    "HouseMediumRoofRight1",
    "HouseMediumRoofRight2",
    "HouseMediumRoofRight3",
    "HouseLargeRoofLeft1",
    "HouseLargeRoofLeft2",
    "HouseLargeRoofLeft3",
    "HouseLargeRoofMiddle1",
    "HouseLargeRoofMiddle2",
    "HouseLargeRoofMiddle3",
    "HouseLargeRoofRight1",
    "HouseLargeRoofRight2",
    "HouseLargeRoofRight3",
    "HouseSmallRoofLeft1",
    "HouseSmallRoofRight1",
    "HouseSmallRoofLeft2",
    "HouseSmallRoofRight2",
    "HouseSmallRoofLeft3",
    "HouseSmallRoofRight3"
  ]]
]
