[registry.SmallHouse.GroundFloor]
Left = ["HouseSmallWallLeft1", "HouseSmallWallLeft2"]
Right = ["HouseSmallWallRight1", "HouseSmallWallRight2"]
LeftDoor = ["HouseSmallDoorLeft"]
RightDoor = ["HouseSmallDoorRight"]

[registry.SmallHouse.Roof]
Left = [
  "HouseSmallRoofLeft1",
  "HouseSmallRoofLeft2",
  "HouseSmallRoofLeft3",
]
Right = [
  "HouseSmallRoofRight1",
  "HouseSmallRoofRight2",
  "HouseSmallRoofRight3",
]

[registry.MediumHouse.GroundFloor]
Left = ["HouseMediumWallLeft"]
Middle = ["HouseMediumWallMiddle1", "HouseMediumWallMiddle2"]
Right = ["HouseMediumWallRight"]
LeftDoor = ["HouseMediumDoorLeft1", "HouseMediumDoorLeft2"]
MiddleDoor = ["HouseMediumDoorMiddle1", "HouseMediumDoorMiddle2"]
RightDoor = ["HouseMediumDoorRight1", "HouseMediumDoorRight2"]

[registry.MediumHouse.Roof]
Left = [
  "HouseMediumRoofLeft1",
  "HouseMediumRoofLeft2",
  "HouseMediumRoofLeft3",
]
Middle = [
  "HouseMediumRoofMiddle1",
  "HouseMediumRoofMiddle2",
  "HouseMediumRoofMiddle3",
]
Right = [
  "HouseMediumRoofRight1",
  "HouseMediumRoofRight2",
  "HouseMediumRoofRight3",
]

[registry.LargeHouse.GroundFloor]
Left = ["HouseLargeWallLeft"]
Middle = ["HouseLargeWallMiddle1", "HouseLargeWallMiddle2"]
Right = ["HouseLargeWallRight"]
LeftDoor = ["HouseLargeDoorLeft1", "HouseLargeDoorLeft2"]
MiddleDoor = ["HouseLargeDoorMiddle1", "HouseLargeDoorMiddle2"]
RightDoor = ["HouseLargeDoorRight1", "HouseLargeDoorRight2"]

[registry.LargeHouse.Roof]
Left = [
  "HouseLargeRoofLeft1",
  "HouseLargeRoofLeft2",
  "HouseLargeRoofLeft3",
]
Middle = [
  "HouseLargeRoofMiddle1",
  "HouseLargeRoofMiddle2",
  "HouseLargeRoofMiddle3",
]
Right = [
  "HouseLargeRoofRight1",
  "HouseLargeRoofRight2",
  "HouseLargeRoofRight3",
]
